# Load UniProt official registry

In [1]:
from collections import defaultdict
from pathlib import Path

import bioregistry as br
import requests

In [2]:
params = {"format": "json", "query": "*", "size": 500}
response = requests.get("https://rest.uniprot.org/database/search", params=params)
response.raise_for_status()
registry_data = response.json()
uniprot_dblist = registry_data["results"]
uniprot_dblist

[{'name': 'ABCD curated depository of sequenced antibodies',
  'id': 'DB-0236',
  'abbrev': 'ABCD',
  'linkType': 'Explicit',
  'servers': ['https://web.expasy.org/abcd'],
  'dbUrl': 'https://web.expasy.org/cgi-bin/abcd/search_abcd.pl?input=%u',
  'category': 'Protocols and materials databases',
  'statistics': {'reviewedProteinCount': 3196, 'unreviewedProteinCount': 619}},
 {'name': 'The Alliance of Genome Resources',
  'id': 'DB-0266',
  'abbrev': 'AGR',
  'pubMedId': '31552413',
  'doiId': '10.1093/nar/gkz813',
  'linkType': 'Explicit',
  'servers': ['https://www.alliancegenome.org/'],
  'dbUrl': 'https://www.alliancegenome.org/gene/%s',
  'category': 'Organism-specific databases',
  'statistics': {'reviewedProteinCount': 68617,
   'unreviewedProteinCount': 246243}},
 {'name': 'Agora',
  'id': 'DB-0283',
  'abbrev': 'Agora',
  'linkType': 'Explicit',
  'servers': ['https://agora.adknowledgeportal.org'],
  'dbUrl': 'https://agora.adknowledgeportal.org/genes/%s/',
  'category': 'Miscellaneous databases',
  'statistics': {'reviewedProteinCount': 18413, 'unreviewedProteinCount': 0}},
 {'name': 'Allergome; a platform for allergen knowledge',
  'id': 'DB-0160',
  'abbrev': 'Allergome',
  'pubMedId': '19671381',
  'doiId': '10.1007/s11882-009-0055-9',
  'linkType': 'Explicit',
  'servers': ['https://www.allergome.org/'],
  'dbUrl': 'https://www.allergome.org/script/dettaglio.php?id_molecule=%s',
  'category': 'Protein family/group databases',
  'statistics': {'reviewedProteinCount': 1316,
   'unreviewedProteinCount': 3081}},
 {'name': 'AlphaFold Protein Structure Database',
  'id': 'DB-0262',
  'abbrev': 'AlphaFoldDB',
  'pubMedId': '37933859',
  'doiId': '10.1093/nar/gkad1011',
  'linkType': 'Explicit',
  'servers': ['https://alphafold.ebi.ac.uk/',
   'https://deepmind.com/research/open-source/alphafold-protein-structure-database'],
  'dbUrl': 'https://alphafold.ebi.ac.uk/search/text/%u',
  'category': '3D structure databases',
  'statistics': {'reviewedProteinCount': 549408,
   'unreviewedProteinCount': 158049481}},
 {'name': 'AntiFam resource to identify spurious protein predictions',
  'id': 'DB-0275',
  'abbrev': 'AntiFam',
  'pubMedId': '22434837',
  'doiId': '10.1093/database/bas003',
  'linkType': 'Explicit',
  'servers': ['https://www.ebi.ac.uk/interpro/entry/antifam'],
  'dbUrl': 'https://www.ebi.ac.uk/interpro/entry/antifam/%s',
  'category': 'Family and domain databases',
  'statistics': {'reviewedProteinCount': 22, 'unreviewedProteinCount': 26090}},
 {'name': 'Antibodypedia a portal for validated antibodies',
  'id': 'DB-0249',
  'abbrev': 'Antibodypedia',
  'pubMedId': '18667413',
  'doiId': '10.1074/mcp.M800264-MCP200',
  'linkType': 'Explicit',
  'servers': ['https://www.antibodypedia.com/'],
  'dbUrl': 'https://www.antibodypedia.com/gene/%s',
  'category': 'Protocols and materials databases',
  'statistics': {'reviewedProteinCount': 32245,
   'unreviewedProteinCount': 71628}},
 {'name': 'ArachnoServer',
  'id': 'DB-0145',
  'abbrev': 'ArachnoServer',
  'pubMedId': '29069336',
  'doiId': '10.1093/bioinformatics/btx661',
  'linkType': 'Explicit',
  'servers': ['http://www.arachnoserver.org'],
  'dbUrl': 'http://www.arachnoserver.org',
  'category': 'Organism-specific databases',
  'statistics': {'reviewedProteinCount': 1138, 'unreviewedProteinCount': 195}},
 {'name': 'Arabidopsis Information Portal',
  'id': 'DB-0221',
  'abbrev': 'Araport',
  'pubMedId': '25414324',
  'doiId': '10.1093/nar/gku1200',
  'linkType': 'Explicit',
  'servers': ['https://bar.utoronto.ca/thalemine/begin.do',
   'https://www.araport.org/'],
  'dbUrl': 'https://bar.utoronto.ca/thalemine/portal.do?externalids=%s',
  'category': 'Organism-specific databases',
  'statistics': {'reviewedProteinCount': 16342,
   'unreviewedProteinCount': 23420}},
 {'name': 'Biological Magnetic Resonance Data Bank',
  'id': 'DB-0256',
  'abbrev': 'BMRB',
  'pubMedId': '36478084',
  'doiId': '10.1093/nar/gkac1050',
  'linkType': 'Explicit',
  'servers': ['https://bmrb.io/'],
  'dbUrl': 'https://bmrb.io/data_library/summary/protein.php?uniprot=%u',
  'category': '3D structure databases',
  'statistics': {'reviewedProteinCount': 6914, 'unreviewedProteinCount': 279}},
 {'name': 'BRENDA Comprehensive Enzyme Information System',
  'id': 'DB-0131',
  'abbrev': 'BRENDA',
  'pubMedId': '33211880',
  'doiId': '10.1093/nar/gkaa1025',
  'linkType': 'Explicit',
  'servers': ['https://www.brenda-enzymes.org'],
  'dbUrl': 'https://www.brenda-enzymes.org/enzyme.php?ecno=%s&UniProtAcc=%u&OrganismID=%d',
  'category': 'Enzyme and pathway databases',
  'statistics': {'reviewedProteinCount': 18683,
   'unreviewedProteinCount': 16399}},
 {'name': 'Bgee dataBase for Gene Expression Evolution',
  'id': 'DB-0133',
  'abbrev': 'Bgee',
  'pubMedId': '33037820',
  'doiId': '10.1093/nar/gkaa793',
  'linkType': 'Explicit',
  'servers': ['https://www.bgee.org'],
  'dbUrl': 'https://www.bgee.org/gene/%s',
  'category': 'Gene expression databases',
  'statistics': {'reviewedProteinCount': 61984,
   'unreviewedProteinCount': 1245174}},
 {'name': 'BindingDB database of measured binding affinities',
  'id': 'DB-0127',
  'abbrev': 'BindingDB',
  'pubMedId': '39574417',
  'doiId': '10.1093/nar/gkae1075',
  'linkType': 'Explicit',
  'servers': ['https://www.bindingdb.org/'],
  'dbUrl': 'https://www.bindingdb.org/rwd/uniprot/%u',
  'category': 'Chemistry databases',
  'statistics': {'reviewedProteinCount': 6929, 'unreviewedProteinCount': 919}},
 {'name': 'BioCyc Collection of Pathway/Genome Databases',
  'id': 'DB-0005',
  'abbrev': 'BioCyc',
  'pubMedId': '29447345',
  'doiId': '10.1093/bib/bbx085',
  'linkType': 'Explicit',
  'servers': ['https://www.biocyc.org/'],
  'dbUrl': 'https://biocyc.org/getid?id=%s',
  'category': 'Enzyme and pathway databases',
  'statistics': {'reviewedProteinCount': 44210,
   'unreviewedProteinCount': 268710}},
 {'name': 'The Biological General Repository for Interaction Datasets (BioGRID)',
  'id': 'DB-0184',
  'abbrev': 'BioGRID',
  'pubMedId': '33070389',
  'doiId': '10.1002/pro.3978',
  'linkType': 'Explicit',
  'servers': ['https://thebiogrid.org/'],
  'dbUrl': 'https://thebiogrid.org/%s',
  'category': 'Protein-protein interaction databases',
  'statistics': {'reviewedProteinCount': 60445, 'unreviewedProteinCount': 1}},
 {'name': 'BioGRID ORCS database of CRISPR phenotype screens',
  'id': 'DB-0252',
  'abbrev': 'BioGRID-ORCS',
  'pubMedId': '30476227',
  'doiId': '10.1093/nar/gky1079',
  'linkType': 'Explicit',
  'servers': ['https://orcs.thebiogrid.org'],
  'dbUrl': 'https://orcs.thebiogrid.org/Gene/%s',
  'category': 'Miscellaneous databases',
  'statistics': {'reviewedProteinCount': 44557,
   'unreviewedProteinCount': 56284}},
 {'name': 'BioMuta curated single-nucleotide variation and disease association database',
  'id': 'DB-0192',
  'abbrev': 'BioMuta',
  'pubMedId': '30053270',
  'doiId': '10.1093/nar/gkx907',
  'linkType': 'Explicit',
  'servers': ['https://hivelab.biochemistry.gwu.edu/biomuta'],
  'dbUrl': 'https://hive.biochemistry.gwu.edu/tools/biomuta/biomuta.php?gene=%s',
  'category': 'Genetic variation databases',
  'statistics': {'reviewedProteinCount': 20259,
   'unreviewedProteinCount': 889}},
 {'name': 'The Comprehensive Antibiotic Resistance Database',
  'id': 'DB-0282',
  'abbrev': 'CARD',
  'pubMedId': '36263822',
  'doiId': '10.1093/nar/gkac920',
  'linkType': 'Explicit',
  'servers': ['https://card.mcmaster.ca'],
  'dbUrl': 'https://card.mcmaster.ca/%s',
  'category': 'Protein family/group databases',
  'statistics': {'reviewedProteinCount': 319, 'unreviewedProteinCount': 3851}},
 {'name': 'Carbohydrate-Active enZymes',
  'id': 'DB-0136',
  'abbrev': 'CAZy',
  'pubMedId': '34850161',
  'doiId': '10.1093/nar/gkab1045',
  'linkType': 'Explicit',
  'servers': ['https://www.cazy.org/'],
  'dbUrl': 'https://www.cazy.org/%s.html',
  'category': 'Protein family/group databases',
  'statistics': {'reviewedProteinCount': 8755,
   'unreviewedProteinCount': 108751}},
 {'name': 'The Consensus CDS (CCDS) project',
  'id': 'DB-0187',
  'abbrev': 'CCDS',
  'pubMedId': '29126148',
  'doiId': '10.1093/nar/gkx1031',
  'linkType': 'Explicit',
  'servers': ['https://www.ncbi.nlm.nih.gov/projects/CCDS/CcdsBrowse.cgi'],
  'dbUrl': 'https://www.ncbi.nlm.nih.gov/CCDS/CcdsBrowse.cgi?REQUEST=CCDS&GO=MainBrowse&DATA=%s',
  'category': 'Sequence databases',
  'statistics': {'reviewedProteinCount': 34842, 'unreviewedProteinCount': 0}},
 {'name': 'CrowDsourcing COndensate Database and Encyclopedia',
  'id': 'DB-0277',
  'abbrev': 'CD-CODE',
  'pubMedId': '37024650',
  'doiId': '10.1038/s41592-023-01831-0',
  'linkType': 'Explicit',
  'servers': ['https://cd-code.org/'],
  'dbUrl': 'https://cd-code.org/condensate/%s',
  'category': 'Miscellaneous databases',
  'statistics': {'reviewedProteinCount': 8219,
   'unreviewedProteinCount': 1453}},
 {'name': 'Conserved Domains Database',
  'id': 'DB-0214',
  'abbrev': 'CDD',
  'pubMedId': '36477806',
  'doiId': '10.1093/nar/gkac1096',
  'linkType': 'Explicit',
  'servers': ['https://www.ncbi.nlm.nih.gov/cdd'],
  'dbUrl': 'https://www.ncbi.nlm.nih.gov/Structure/cdd/cddsrv.cgi?uid=%s',
  'category': 'Family and domain databases',
  'statistics': {'reviewedProteinCount': 309774,
   'unreviewedProteinCount': 67075747}},
 {'name': 'Candida Genome Database',
  'id': 'DB-0126',
  'abbrev': 'CGD',
  'pubMedId': '27738138',
  'doiId': '10.1093/nar/gkw924',
  'linkType': 'Explicit',
  'servers': ['http://www.candidagenome.org/'],
  'dbUrl': 'http://www.candidagenome.org/cgi-bin/locus.pl?dbid=%s',
  'category': 'Organism-specific databases',
  'statistics': {'reviewedProteinCount': 2143,
   'unreviewedProteinCount': 20526}},
 {'name': 'CIViC Clinical Interpretation of Variants in Cancer',
  'id': 'DB-0284',
  'abbrev': 'CIViC',
  'pubMedId': '28138153',
  'doiId': '110.1038/ng.3774',
  'linkType': 'Explicit',
  'servers': ['https://civicdb.org'],
  'dbUrl': 'https://civicdb.org/links/entrez_id/%s',
  'category': 'Organism-specific databases',
  'statistics': {'reviewedProteinCount': 568, 'unreviewedProteinCount': 0}},
 {'name': 'CORUM comprehensive resource of mammalian protein complexes',
  'id': 'DB-0224',
  'abbrev': 'CORUM',
  'pubMedId': '36382402',
  'doiId': '10.1093/nar/gkac1015',
  'linkType': 'Explicit',
  'servers': ['https://mips.helmholtz-muenchen.de/corum/'],
  'dbUrl': 'https://mips.helmholtz-muenchen.de/corum/#?uniprotID=%u',
  'category': 'Protein-protein interaction databases',
  'statistics': {'reviewedProteinCount': 8090, 'unreviewedProteinCount': 349}},
 {'name': 'The CPTAC Assay portal',
  'id': 'DB-0238',
  'abbrev': 'CPTAC',
  'pubMedId': '24972168',
  'doiId': '10.1038/nmeth.3002',
  'linkType': 'Explicit',
  'servers': ['https://assays.cancer.gov/'],
  'dbUrl': 'https://assays.cancer.gov/%s',
  'category': 'Proteomic databases',
  'statistics': {'reviewedProteinCount': 1929, 'unreviewedProteinCount': 13}},
 {'name': 'The CPTC Antibody Portal',
  'id': 'DB-0259',
  'abbrev': 'CPTC',
  'linkType': 'Explicit',
  'servers': ['https://antibodies.cancer.gov'],
  'dbUrl': 'https://antibodies.cancer.gov/uniprot/%u',
  'category': 'Protocols and materials databases',
  'statistics': {'reviewedProteinCount': 410, 'unreviewedProteinCount': 0}},
 {'name': 'Comparative Toxicogenomics Database',
  'id': 'DB-0140',
  'abbrev': 'CTD',
  'pubMedId': '33068428',
  'doiId': '10.1093/nar/gkaa891',
  'linkType': 'Explicit',
  'servers': ['https://ctdbase.org/'],
  'dbUrl': 'https://ctdbase.org/detail.go?type=gene&db=GENE&acc=%s',
  'category': 'Organism-specific databases',
  'statistics': {'reviewedProteinCount': 77047,
   'unreviewedProteinCount': 3968516}},
 {'name': 'CarbonylDB database of protein carbonylation sites',
  'id': 'DB-0225',
  'abbrev': 'CarbonylDB',
  'pubMedId': '29509874',
  'doiId': '10.1093/bioinformatics/bty123',
  'linkType': 'Explicit',
  'servers': ['https://carbonyldb.missouri.edu/CarbonylDB/index.php'],
  'dbUrl': 'https://carbonyldb.missouri.edu/CarbonylDB/index.php/detail/protein/%u',
  'category': 'PTM databases',
  'statistics': {'reviewedProteinCount': 1159, 'unreviewedProteinCount': 305}},
 {'name': 'ChEMBL database of bioactive drug-like small molecules',
  'id': 'DB-0174',
  'abbrev': 'ChEMBL',
  'pubMedId': '37933841',
  'doiId': '10.1093/nar/gkad1004',
  'linkType': 'Explicit',
  'servers': ['https://www.ebi.ac.uk/chembl'],
  'dbUrl': 'https://www.ebi.ac.uk/chembl/target_report_card/%s',
  'category': 'Chemistry databases',
  'statistics': {'reviewedProteinCount': 9110,
   'unreviewedProteinCount': 1179}},
 {'name': 'ChiTaRS',
  'id': 'DB-0176',
  'abbrev': 'ChiTaRS',
  'pubMedId': '39676654',
  'doiId': '10.1093/nar/gkae1126',
  'linkType': 'Explicit',
  'servers': ['http://biosrv.org/chmb/information'],
  'dbUrl': 'http://biosrv.org/chmb/search?GEN=%s',
  'category': 'Miscellaneous databases',
  'statistics': {'reviewedProteinCount': 15251,
   'unreviewedProteinCount': 107098}},
 {'name': 'The ClinGen clinical relevance of genes and variants resource',
  'id': 'DB-0263',
  'abbrev': 'ClinGen',
  'pubMedId': '26014595',
  'doiId': '10.1056/NEJMsr1406261',
  'linkType': 'Implicit',
  'servers': ['https://www.clinicalgenome.org/'],
  'dbUrl': 'https://search.clinicalgenome.org/kb/genes/%s',
  'category': 'Genetic variation databases',
  'statistics': {'reviewedProteinCount': 0, 'unreviewedProteinCount': 0}},
 {'name': 'The Clinical Pharmacogenomics Resource',
  'id': 'DB-0285',
  'abbrev': 'ClinPGx',
  'pubMedId': '34216021',
  'doiId': '10.1002/cpt.2350',
  'linkType': 'Explicit',
  'servers': ['https://www.clinpgx.org'],
  'dbUrl': 'https://www.clinpgx.org/gene/%s',
  'category': 'Organism-specific databases',
  'statistics': {'reviewedProteinCount': 18009,
   'unreviewedProteinCount': 3064}},
 {'name': 'CollecTF database of bacterial transcription factor binding sites',
  'id': 'DB-0198',
  'abbrev': 'CollecTF',
  'pubMedId': '24234444',
  'doiId': '10.1093/nar/gkt1087',
  'linkType': 'Explicit',
  'servers': ['http://www.collectf.org/'],
  'dbUrl': 'http://www.collectf.org/%s',
  'category': 'Gene expression databases',
  'statistics': {'reviewedProteinCount': 138, 'unreviewedProteinCount': 163}},
 {'name': 'ComplexPortal',
  'id': 'DB-0228',
  'abbrev': 'ComplexPortal',
  'pubMedId': '30357405',
  'doiId': '10.1093/nar/gky1001',
  'linkType': 'Explicit',
  'servers': ['https://www.ebi.ac.uk/complexportal/'],
  'dbUrl': 'https://www.ebi.ac.uk/complexportal/complex/%s',
  'category': 'Protein-protein interaction databases',
  'statistics': {'reviewedProteinCount': 9733, 'unreviewedProteinCount': 716}},
 {'name': 'ConoServer',
  'id': 'DB-0156',
  'abbrev': 'ConoServer',
  'pubMedId': '22058133',
  'doiId': '10.1093/nar/gkr886',
  'linkType': 'Explicit',
  'servers': ['https://www.conoserver.org/'],
  'dbUrl': 'https://www.conoserver.org/?page=card&table=protein&id=%s',
  'category': 'Organism-specific databases',
  'statistics': {'reviewedProteinCount': 879, 'unreviewedProteinCount': 157}},
 {'name': 'DNA Data Bank of Japan; a nucleotide sequence database',
  'id': 'DB-0014',
  'abbrev': 'DDBJ',
  'pubMedId': '36420889',
  'doiId': '10.1093/nar/gkac1083',
  'linkType': 'Implicit',
  'servers': ['https://www.ddbj.nig.ac.jp/index-e.html'],
  'dbUrl': 'https://getentry.ddbj.nig.ac.jp/getentry/na/%s?filetype=html',
  'category': 'Sequence databases',
  'statistics': {'reviewedProteinCount': 0, 'unreviewedProteinCount': 0}},
 {'name': 'DEPOD human dephosphorylation database',
  'id': 'DB-0190',
  'abbrev': 'DEPOD',
  'pubMedId': '31836896',
  'doiId': 'doi',
  'linkType': 'Explicit',
  'servers': ['https://depod.bioss.uni-freiburg.de'],
  'dbUrl': 'https://depod.bioss.uni-freiburg.de/showp.php?name=%s',
  'category': 'PTM databases',
  'statistics': {'reviewedProteinCount': 254, 'unreviewedProteinCount': 0}},
 {'name': 'Database of interacting proteins',
  'id': 'DB-0016',
  'abbrev': 'DIP',
  'pubMedId': '14681454',
  'doiId': '10.1093/nar/gkh086',
  'linkType': 'Explicit',
  'servers': ['https://dip.doe-mbi.ucla.edu/'],
  'dbUrl': 'https://dip.doe-mbi.ucla.edu/dip/Browse.cgi?ID=%s',
  'category': 'Protein-protein interaction databases',
  'statistics': {'reviewedProteinCount': 17539,
   'unreviewedProteinCount': 2949}},
 {'name': 'Domain mapping of disease mutations (DMDM)',
  'id': 'DB-0166',
  'abbrev': 'DMDM',
  'pubMedId': '20685956',
  'doiId': '10.1093/bioinformatics/btq447',
  'linkType': 'Explicit',
  'servers': ['https://bioinf.umbc.edu/dmdm/'],
  'dbUrl': 'https://bioinf.umbc.edu/dmdm/gene_prot_page.php?search_type=protein&id=%s',
  'category': 'Genetic variation databases',
  'statistics': {'reviewedProteinCount': 16163, 'unreviewedProteinCount': 0}},
 {'name': 'The DNASU plasmid repository',
  'id': 'DB-0167',
  'abbrev': 'DNASU',
  'pubMedId': '24225319',
  'doiId': '10.1093/nar/gkt1060',
  'linkType': 'Explicit',
  'servers': ['https://dnasu.org/DNASU/'],
  'dbUrl': 'https://dnasu.org/DNASU/AdvancedSearchOptions.do?geneName=%s',
  'category': 'Protocols and materials databases',
  'statistics': {'reviewedProteinCount': 48477,
   'unreviewedProteinCount': 87491}},
 {'name': 'DisGeNET',
  'id': 'DB-0218',
  'abbrev': 'DisGeNET',
  'pubMedId': '31680165',
  'doiId': '10.1093/nar/gkz1021',
  'linkType': 'Explicit',
  'servers': ['https://www.disgenet.com/'],
  'dbUrl': 'https://www.disgenet.com/search?view=GENES&idents=%s&source=ALL&tab=GDA',
  'category': 'Organism-specific databases',
  'statistics': {'reviewedProteinCount': 17415,
   'unreviewedProteinCount': 11508}},
 {'name': 'Database of protein disorder',
  'id': 'DB-0017',
  'abbrev': 'DisProt',
  'pubMedId': '34850135',
  'doiId': '10.1093/nar/gkab1082',
  'linkType': 'Explicit',
  'servers': ['https://disprot.org'],
  'dbUrl': 'https://disprot.org/%s',
  'category': 'Family and domain databases',
  'statistics': {'reviewedProteinCount': 2800, 'unreviewedProteinCount': 370}},
 {'name': 'Drug and drug target database',
  'id': 'DB-0019',
  'abbrev': 'DrugBank',
  'pubMedId': '37953279',
  'doiId': '10.1093/nar/gkad976',
  'linkType': 'Explicit',
  'servers': ['https://go.drugbank.com'],
  'dbUrl': 'https://go.drugbank.com/drugs/%s',
  'category': 'Chemistry databases',
  'statistics': {'reviewedProteinCount': 4939, 'unreviewedProteinCount': 406}},
 {'name': 'DrugCentral',
  'id': 'DB-0239',
  'abbrev': 'DrugCentral',
  'pubMedId': '36484092',
  'doiId': '10.1093/nar/gkac1085',
  'linkType': 'Explicit',
  'servers': ['https://drugcentral.org/'],
  'dbUrl': 'https://drugcentral.org?q=%u',
  'category': 'Chemistry databases',
  'statistics': {'reviewedProteinCount': 2982, 'unreviewedProteinCount': 288}},
 {'name': 'The Eukaryotic Linear Motif resource for Functional Sites in Proteins',
  'id': 'DB-0223',
  'abbrev': 'ELM',
  'pubMedId': '34718738',
  'doiId': '10.1093/nar/gkab975',
  'linkType': 'Explicit',
  'servers': ['http://elm.eu.org/'],
  'dbUrl': 'http://elm.eu.org/instances.html?q=%u',
  'category': 'Protein-protein interaction databases',
  'statistics': {'reviewedProteinCount': 1815, 'unreviewedProteinCount': 76}},
 {'name': 'EMBL nucleotide sequence database',
  'id': 'DB-0022',
  'abbrev': 'EMBL',
  'pubMedId': '33175160',
  'doiId': '10.1093/nar/gkaa1028',
  'linkType': 'Explicit',
  'servers': ['https://www.ebi.ac.uk/ena/browser/home'],
  'dbUrl': 'https://www.ebi.ac.uk/ena/browser/view/%s',
  'category': 'Sequence databases',
  'statistics': {'reviewedProteinCount': 561609,
   'unreviewedProteinCount': 185502674}},
 {'name': 'Electron Microscopy Data Bank',
  'id': 'DB-0272',
  'abbrev': 'EMDB',
  'pubMedId': '26578576',
  'doiId': '10.1093/nar/gkv1126',
  'linkType': 'Explicit',
  'servers': ['https://www.ebi.ac.uk/emdb'],
  'dbUrl': 'https://www.ebi.ac.uk/emdb/%s',
  'category': '3D structure databases',
  'statistics': {'reviewedProteinCount': 11682,
   'unreviewedProteinCount': 9896}},
 {'name': 'Enzyme nomenclature database',
  'id': 'DB-0024',
  'abbrev': 'ENZYME',
  'pubMedId': '10592255',

In [3]:
uniprot_dblist_db_names = {
    entry["name"].strip().lower() for entry in registry_data["results"] if isinstance(entry, dict) and entry.get("name")
}

print("Official UniProt name count:", len(uniprot_dblist_db_names))

uniprot_dblist_prefixes = {
    entry["abbrev"].strip().lower()
    for entry in registry_data["results"]
    if isinstance(entry, dict) and entry.get("abbrev")
}

print("Official UniProt abbrev count:", len(uniprot_dblist_prefixes))
uniprot_dblist_prefixes

Official UniProt name count: 185
Official UniProt abbrev count: 185

{'abcd',
 'agora',
 'agr',
 'allergome',
 'alphafolddb',
 'antibodypedia',
 'antifam',
 'arachnoserver',
 'araport',
 'bgee',
 'bindingdb',
 'biocyc',
 'biogrid',
 'biogrid-orcs',
 'biomuta',
 'bmrb',
 'brenda',
 'carbonyldb',
 'card',
 'cazy',
 'ccds',
 'cd-code',
 'cdd',
 'cgd',
 'chembl',
 'chitars',
 'civic',
 'clingen',
 'clinpgx',
 'collectf',
 'complexportal',
 'conoserver',
 'corum',
 'cptac',
 'cptc',
 'ctd',
 'dbsnp',
 'ddbj',
 'depod',
 'dictybase',
 'dip',
 'disgenet',
 'disprot',
 'dmdm',
 'dnasu',
 'drugbank',
 'drugcentral',
 'echobase',
 'eggnog',
 'elm',
 'embl',
 'emdb',
 'ensembl',
 'ensemblbacteria',
 'ensemblfungi',
 'ensemblmetazoa',
 'ensemblplants',
 'ensemblprotists',
 'enzyme',
 'esther',
 'euhcvdb',
 'evolutionarytrace',
 'expressionatlas',
 'flybase',
 'funcoup',
 'funfam',
 'genatlas',
 'genbank',
 'gencc',
 'gene3d',
 'genecards',
 'geneid',
 'genereviews',
 'genetree',
 'genewiki',
 'genomernai',
 'glyconnect',
 'glycosmos',
 'glygen',
 'go',
 'gpcrdb',
 'gramene',
 'guidetopharmacology',
 'hamap',
 'hgnc',
 'hogenom',
 'hpa',
 'huge',
 'ideal',
 'imgt_gene-db',
 'inparanoid',
 'intact',
 'interpro',
 'iptmnet',
 'japonicusdb',
 'jpost',
 'kegg',
 'legiolist',
 'leproma',
 'maizegdb',
 'malacards',
 'mane-select',
 'massive',
 'merops',
 'metosite',
 'mgi',
 'mim',
 'mint',
 'mobidb',
 'modbase',
 'moondb',
 'moonprot',
 'ncbifam',
 'niagads',
 'ogp',
 'oma',
 'opentargets',
 'orphanet',
 'orthodb',
 'pan-go',
 'panther',
 'pathwaycommons',
 'patric',
 'paxdb',
 'pcddb',
 'pdb',
 'pdbe-kb',
 'pdbj',
 'pdbsum',
 'peptideatlas',
 'peroxibase',
 'pfam',
 'pharos',
 'phi-base',
 'phosphositeplus',
 'phylomedb',
 'pir',
 'pirsf',
 'plantreactome',
 'pombase',
 'pride',
 'prints',
 'pro',
 'promex',
 'prosite',
 'proteomes',
 'proteomicsdb',
 'pseudocap',
 'pumba',
 'rcsb-pdb',
 'reactome',
 'rebase',
 'refseq',
 'reproduction-2dpage',
 'rgd',
 'rnact',
 'rouge',
 'sabio-rk',
 'sasbdb',
 'sfld',
 'sgd',
 'signalink',
 'signor',
 'smart',
 'smr',
 'strenda-db',
 'string',
 'supfam',
 'swiss-model-workspace',
 'swisslipids',
 'swisspalm',
 'tair',
 'tcdb',
 'topdownproteomics',
 'tuberculist',
 'ucsc',
 'unilectin',
 'unipathway',
 'veupathdb',
 'vgnc',
 'wbparasite',
 'wormbase',
 'xenbase',
 'ycharos',
 'zfin'}

## Load ID mapping prefixes.txt

List of all unique prefixes that appear in the UniProt ID mapping data file: 
[idmapping.dat.gz](https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/idmapping.dat.gz)

In [4]:
ID_MAPPING_PREFIXES = Path("data/prefixes.txt")
idmapping_prefixes = {line.strip().lower() for line in ID_MAPPING_PREFIXES.read_text().split("\n") if line.strip()}
print("UniProt ID mapping prefixes:", len(idmapping_prefixes))
idmapping_prefixes

UniProt ID mapping prefixes: 103

{'allergome',
 'arachnoserver',
 'araport',
 'biocyc',
 'biogrid',
 'biomuta',
 'ccds',
 'cgd',
 'chembl',
 'chitars',
 'collectf',
 'complexportal',
 'conoserver',
 'cptac',
 'crc64',
 'dictybase',
 'dip',
 'disprot',
 'dmdm',
 'dnasu',
 'drugbank',
 'echobase',
 'eggnog',
 'embl',
 'embl-cds',
 'emdb',
 'ensembl',
 'ensembl_pro',
 'ensembl_trs',
 'ensemblgenome',
 'ensemblgenome_pro',
 'ensemblgenome_trs',
 'esther',
 'euhcvdb',
 'flybase',
 'gene_name',
 'gene_orderedlocusname',
 'gene_orfname',
 'gene_synonym',
 'genecards',
 'geneid',
 'genereviews',
 'genetree',
 'genewiki',
 'genomernai',
 'gi',
 'glyconnect',
 'guidetopharmacology',
 'hgnc',
 'hogenom',
 'ideal',
 'japonicusdb',
 'kegg',
 'legiolist',
 'leproma',
 'maizegdb',
 'merops',
 'mgi',
 'mim',
 'mint',
 'ncbi_taxid',
 'nextprot',
 'oma',
 'opentargets',
 'orphanet',
 'orthodb',
 'patric',
 'pdb',
 'peroxibase',
 'pharmgkb',
 'phi-base',
 'plantreactome',
 'pombase',
 'proteomicsdb',
 'pseudocap',
 'reactome',
 'rebase',
 'refseq',
 'refseq_nt',
 'rgd',
 'sgd',
 'string',
 'swisslipids',
 'tair',
 'tcdb',
 'treefam',
 'tuberculist',
 'ucsc',
 'uniparc',
 'unipathway',
 'uniprotkb-id',
 'uniref100',
 'uniref50',
 'uniref90',
 'veupathdb',
 'vgnc',
 'wbparasite',
 'wbparasite_trs_pro',
 'wormbase',
 'wormbase_pro',
 'wormbase_trs',
 'xenbase',
 'zfin'}

In [5]:
## Prefixes in the ID mapping file but not in UniProt official list
idmapping_not_in_dblist = idmapping_prefixes - uniprot_dblist_prefixes
print(len(idmapping_not_in_dblist))
print(sorted(idmapping_not_in_dblist))

25
['crc64', 'embl-cds', 'ensembl_pro', 'ensembl_trs', 'ensemblgenome', 'ensemblgenome_pro', 'ensemblgenome_trs', 'gene_name', 'gene_orderedlocusname', 'gene_orfname', 'gene_synonym', 'gi', 'ncbi_taxid', 'nextprot', 'pharmgkb', 'refseq_nt', 'treefam', 'uniparc', 'uniprotkb-id', 'uniref100', 'uniref50', 'uniref90', 'wbparasite_trs_pro', 'wormbase_pro', 'wormbase_trs']

### Classification of ID Mapping Prefixes Not Present in UniProt Official Cross-Reference Registry

The following prefixes appear in the ID mapping-derived set but are not listed in the UniProt official cross-reference registry.

They fall into several categories:

1.	Internal UniProt metadata
2.	Subtype mappings 
3.	External biological databases
4.	Deprecated or taxonomy identifiers
5.	UniProt-derived resources

In [6]:
## create a dictionary with empty lists
classification = defaultdict(list)

SUBTYPE_MAPPING = {
    "embl-cds",  # EMBL CDS subtype
    "refseq_nt",  # RefSeq nucleotide subtype
}

for p in sorted(idmapping_not_in_dblist):
    # internal annotation fields
    if p.startswith("gene_") or p in {"crc64", "uniprotkb-id"}:
        classification["internal_metadata"].append(p)

    # UniProt derived databases
    elif p.startswith("uniref") or p == "uniparc":
        classification["uniprot_derived_db"].append(p)

    # subtype-specific identifiers
    elif p in SUBTYPE_MAPPING or any(token in p for token in ["_pro", "_trs"]):
        classification["subtype_mapping"].append(p)

    # deprecated identifiers
    elif p == "gi":
        classification["deprecated_identifier"].append(p)

    # taxonomy identifiers
    elif p == "ncbi_taxid":
        classification["taxonomy_identifier"].append(p)

    # external database candidate
    else:
        classification["external_database_candidate"].append(p)

for k, v in classification.items():
    print(f"\n{k} ({len(v)}):")
    print(sorted(v))

internal_metadata (6):
['crc64', 'gene_name', 'gene_orderedlocusname', 'gene_orfname', 'gene_synonym', 'uniprotkb-id']

subtype_mapping (9):
['embl-cds', 'ensembl_pro', 'ensembl_trs', 'ensemblgenome_pro', 'ensemblgenome_trs', 'refseq_nt', 'wbparasite_trs_pro', 'wormbase_pro', 'wormbase_trs']

external_database_candidate (4):
['ensemblgenome', 'nextprot', 'pharmgkb', 'treefam']

deprecated_identifier (1):
['gi']

taxonomy_identifier (1):
['ncbi_taxid']

uniprot_derived_db (4):
['uniparc', 'uniref100', 'uniref50', 'uniref90']

## Load parquet prefixes

The following code must be run on BERDL.

In [7]:
from berdl_notebook_utils.setup_spark_session import get_spark_session
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lower

In [8]:
spark = get_spark_session("PrefixExploration")

In [12]:
# Load the identifier table from the uniprot raw dataset on BERDL
# this dataset has already been partitioned by `db` column to make it quicker to access
df = spark.read.parquet(
    "s3a://cdm-lake/tenant-general-warehouse/kbase/datasets/uniprot/uniprot_kb/identifier_partitioned"
)
df.printSchema()
# get the distinct prefixes from the identifier table
identifier_table_dbs = {d.asDict().get("db") for d in df.select("db").distinct().collect()}
print("Databases in the `identifiers` table:")
identifier_table_dbs

root
 |-- entity_id: string (nullable = true)
 |-- db: string (nullable = true)
 |-- xref: string (nullable = true)
 |-- description: string (nullable = true)
 |-- _dlt_load_id: string (nullable = true)
 |-- _dlt_id: string (nullable = true)
 |-- relationship: string (nullable = true)

Databases in the `identifiers` table:

{'ABCD',
 'AGR',
 'Agora',
 'Allergome',
 'AlphaFoldDB',
 'AntiFam',
 'Antibodypedia',
 'ArachnoServer',
 'Araport',
 'BMRB',
 'BRENDA',
 'Bgee',
 'BindingDB',
 'BioCyc',
 'BioGRID',
 'BioGRID-ORCS',
 'BioMuta',
 'CARD',
 'CAZy',
 'CCDS',
 'CD-CODE',
 'CDD',
 'CGD',
 'CIViC',
 'CORUM',
 'CPTAC',
 'CPTC',
 'CTD',
 'CarbonylDB',
 'ChEMBL',
 'ChiTaRS',
 'ClinPGx',
 'CollecTF',
 'ComplexPortal',
 'ConoServer',
 'DEPOD',
 'DIP',
 'DMDM',
 'DNASU',
 'DisGeNET',
 'DisProt',
 'DrugBank',
 'DrugCentral',
 'EC',
 'ELM',
 'EMDB',
 'ESTHER',
 'EchoBASE',
 'EnsemblBacteria',
 'EnsemblFungi',
 'EnsemblMetazoa',
 'EnsemblPlants',
 'EnsemblProtists',
 'EvolutionaryTrace',
 'ExpressionAtlas',
 'FlyBase',
 'FunCoup',
 'FunFam',
 'GO',
 'Gene3D',
 'GeneCards',
 'GeneID',
 'GeneReviews',
 'GeneTree',
 'GeneWiki',
 'GenomeRNAi',
 'GlyConnect',
 'GlyCosmos',
 'GlyGen',
 'Gramene',
 'GuidetoPHARMACOLOGY',
 'HAMAP',
 'HGNC',
 'HOGENOM',
 'HPA',
 'IDEAL',
 'IMGT_GENE-DB',
 'InParanoid',
 'IntAct',
 'InterPro',
 'JaponicusDB',
 'KEGG',
 'LegioList',
 'Leproma',
 'MEROPS',
 'MGI',
 'MIM',
 'MINT',
 'MaizeGDB',
 'MalaCards',
 'MassIVE',
 'MetOSite',
 'MoonDB',
 'MoonProt',
 'NCBITaxon',
 'NCBIfam',
 'NIAGADS',
 'OGP',
 'OMA',
 'OpenTargets',
 'Orphanet',
 'OrthoDB',
 'PAN-GO',
 'PANTHER',
 'PATRIC',
 'PCDDB',
 'PDB',
 'PDBsum',
 'PHI-base',
 'PIR',
 'PIRSF',
 'PRIDE',
 'PRINTS',
 'PRO',
 'PROSITE',
 'PathwayCommons',
 'PaxDb',
 'PeptideAtlas',
 'PeroxiBase',
 'Pfam',
 'Pharos',
 'PhosphoSitePlus',
 'PhylomeDB',
 'PlantReactome',
 'PomBase',
 'ProMEX',
 'Proteomes',
 'ProteomicsDB',
 'PseudoCAP',
 'Pumba',
 'REBASE',
 'REPRODUCTION-2DPAGE',
 'RGD',
 'RNAct',
 'Reactome',
 'SABIO-RK',
 'SASBDB',
 'SFLD',
 'SGD',
 'SIGNOR',
 'SMART',
 'SMR',
 'STRENDA-DB',
 'STRING',
 'SUPFAM',
 'SignaLink',
 'SwissLipids',
 'SwissPalm',
 'TAIR',
 'TCDB',
 'TopDownProteomics',
 'TubercuList',
 'UCSC',
 'UniLectin',
 'UniPathway',
 'UniProt',
 'VEuPathDB',
 'VGNC',
 'WBParaSite',
 'WormBase',
 'Xenbase',
 'YCharOS',
 'ZFIN',
 'dictyBase',
 'eggNOG',
 'ensembl',
 'euHCVdb',
 'genbank',
 'iPTMnet',
 'jPOST',
 'refseq'}

In [15]:
# save the identifier table db prefixes to file for easier querying without needing BERDL access
outfile = Path("data") / "identifier_table_prefixes.txt"
outfile.write_text("\n".join(sorted(identifier_table_dbs)))

1421

In [23]:
parquet_set = {db.lower() for db in identifier_table_dbs}
print("Parquet prefixes:", len(parquet_set))
print(parquet_set)

Parquet prefixes: 171
{'ensemblprotists', 'peroxibase', 'strenda-db', 'civic', 'swisslipids', 'funfam', 'mgi', 'pro', 'corum', 'sfld', 'hogenom', 'biocyc', 'peptideatlas', 'echobase', 'drugbank', 'tuberculist', 'allergome', 'carbonyldb', 'prints', 'antibodypedia', 'smr', 'supfam', 'phosphositeplus', 'jpost', 'chitars', 'reactome', 'tair', 'expressionatlas', 'ncbitaxon', 'genewiki', 'esther', 'genbank', 'pumba', 'genereviews', 'panther', 'rgd', 'proteomes', 'malacards', 'moondb', 'flybase', 'araport', 'hpa', 'agora', 'ensemblbacteria', 'reproduction-2dpage', 'cgd', 'funcoup', 'disgenet', 'sgd', 'inparanoid', 'ncbifam', 'glyconnect', 'ycharos', 'moonprot', 'phylomedb', 'pombase', 'dmdm', 'prosite', 'hamap', 'pir', 'orphanet', 'swisspalm', 'dictybase', 'ensemblfungi', 'glycosmos', 'japonicusdb', 'clinpgx', 'bindingdb', 'glygen', 'interpro', 'vgnc', 'arachnoserver', 'ensemblmetazoa', 'sabio-rk', 'string', 'gene3d', 'sasbdb', 'ccds', 'drugcentral', 'abcd', 'legiolist', 'opentargets', 'metosite', 'cd-code', 'imgt_gene-db', 'pirsf', 'go', 'niagads', 'emdb', 'gramene', 'pathwaycommons', 'veupathdb', 'ensemblplants', 'complexportal', 'ec', 'oma', 'topdownproteomics', 'patric', 'plantreactome', 'genomernai', 'pharos', 'biogrid-orcs', 'unilectin', 'rebase', 'cptc', 'maizegdb', 'eggnog', 'dnasu', 'evolutionarytrace', 'unipathway', 'cazy', 'pdb', 'euhcvdb', 'geneid', 'mint', 'ogp', 'depod', 'pdbsum', 'wormbase', 'signor', 'ctd', 'ucsc', 'elm', 'intact', 'pan-go', 'orthodb', 'uniprot', 'kegg', 'bmrb', 'bgee', 'disprot', 'iptmnet', 'smart', 'agr', 'pride', 'antifam', 'zfin', 'genetree', 'signalink', 'brenda', 'leproma', 'proteomicsdb', 'wbparasite', 'genecards', 'hgnc', 'rnact', 'cptac', 'refseq', 'pseudocap', 'paxdb', 'tcdb', 'phi-base', 'merops', 'collectf', 'pcddb', 'mim', 'ensembl', 'promex', 'chembl', 'pfam', 'cdd', 'biomuta', 'ideal', 'alphafolddb', 'conoserver', 'guidetopharmacology', 'dip', 'biogrid', 'card', 'xenbase', 'massive'}

In [26]:
## Prefixes in parquet but not in UniProt official list
parquet_not_in_uniprot = parquet_set - uniprot_dblist_prefixes
print(
    f"Prefixes in the Identifier table that don't appear in the UniProt dblist prefixes ({len(parquet_not_in_uniprot)}):"
)
print(sorted(parquet_not_in_uniprot))

Prefixes in the Identifier table that don't appear in the UniProt dblist prefixes (3):
['ec', 'ncbitaxon', 'uniprot']

### Interpretation

These are not true registry gaps:

- **ec** – Represents EC numbers. 
- **ncbitaxon** – A naming variation of NCBI Taxonomy.
- **uniprot** – UniProt itself is not listed as an external cross-reference database.

Conclusion: No external databases detected

In [27]:
external_candidates = classification["external_database_candidate"]

In [28]:
for p in external_candidates:
    in_name = p in uniprot_dblist_db_names
    in_abbrev = p in uniprot_dblist_prefixes
    in_parquet = p in parquet_set
    print(f"{p:20} | name={in_name} | abbrev={in_abbrev}| parquet={in_parquet}")

ensemblgenome        | name=False | abbrev=False| parquet=False
nextprot             | name=False | abbrev=False| parquet=False
pharmgkb             | name=False | abbrev=False| parquet=False
treefam              | name=False | abbrev=False| parquet=False

Some prefixes classified as external database candidates (e.g., nextprot, pharmgkb, treefam) do not currently appear in the BERDL parquet dataset.

This indicates that while these namespaces correspond to real biological databases, they are not used in the current dataset snapshot. They remain classified as external databases based on their semantic meaning rather than dataset usage.

# Classification of Differences

### A. UniProt annotation metadata 
- crc64
- gene_name
- gene_orderedlocusname
- gene_orfname
- gene_synonym
- uniprotkb-id

These fields represent internal UniProt annotations rather than cross-references to external databases. Examples include gene name annotations and sequence checksums maintained directly within UniProt records.

### B. UniProt derived databases 
- uniparc 
- uniref100
- uniref50
- uniref90

These are UniProt internal resources, no need remapping.

### C. Internal NCBI identifiers
- gi
- ncbi_taxid
  
ncbi_taxid is taxonomy identifier,
gi used by NCBI but has been officially deprecated.

### D. Database subtype mappings 
- embl-cds
- refseq_nt
- ensembl_pro
- ensembl_trs
- ensemblgenome_pro
- ensemblgenome_trs
- wormbase_pro
- wormbase_trs
- wbparasite_trs_pro

#### patterns:
- `_pro` → protein identifiers
- `_trs` → transcript identifiers
- `_cds` → coding sequence identifiers
- `_nt` → nucleotide accessions

These indicate the identifier type within a parent database. Need normalize to parent database prefix.

### E. External database 

- ensemblgenome
- nextprot
- pharmgkb
- treefam

#### examples

- `EnsemblGenome` – genome annotation database
- `NextProt` – human protein knowledgebase
- `PharmGKB` – pharmacogenomics database
- `TreeFam` – phylogenetic gene family database

In [29]:
prefixes = sorted(idmapping_not_in_dblist)
results = []

for p in prefixes:
    resource = br.get_resource(p)
    normalized = br.normalize_prefix(p)

    results.append({"prefix": p, "bioregistry_found": resource is not None, "normalized": normalized})

for r in results:
    print(r)

{'prefix': 'crc64', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'embl-cds', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'ensembl_pro', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'ensembl_trs', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'ensemblgenome', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'ensemblgenome_pro', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'ensemblgenome_trs', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'gene_name', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'gene_orderedlocusname', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'gene_orfname', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'gene_synonym', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'gi', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'ncbi_taxid', 'bioregistry_found': True, 'normalized': 'ncbitaxon'}
{'prefix': 'nextprot', 'bioregistry_found': True, 'normalized': 'nextprot'}
{'prefix': 'pharmgkb', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'refseq_nt', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'treefam', 'bioregistry_found': True, 'normalized': 'treefam'}
{'prefix': 'uniparc', 'bioregistry_found': True, 'normalized': 'uniparc'}
{'prefix': 'uniprotkb-id', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'uniref100', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'uniref50', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'uniref90', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'wbparasite_trs_pro', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'wormbase_pro', 'bioregistry_found': False, 'normalized': None}
{'prefix': 'wormbase_trs', 'bioregistry_found': False, 'normalized': None}

## conclusion 

The Bioregistry package partially support prefix remapping, but it is not sufficient as a solution for the UniProt / BERDL prefix governance workflow.

### Bioregistry package effective for: 

- Canonical prefix normalization
- Synonym resolution (e.g., ncbi_taxid → ncbitaxon)
- Validation of recognized external biological databases

### Bioregistry does not cover: 

- Subtype-specific identifiers (e.g., ensembl_pro, refseq_nt)
- UniProt internal metadata fields (e.g., gene_name, crc64)
- UniProt-derived internal resources (e.g., uniref100)
- Deprecated identifiers, requires manual handling or exclusion (e.g., gi)

In [30]:
INTERNAL_PREFIXES = set(classification.get("internal_metadata", []))

## subtype has feature, xxx_pro/xxx_trs/xxx_nt/xxx_cds
SUBTYPE_TOKENS = {"pro", "trs", "nt", "cds"}


def infer_parent_prefix(prefix: str) -> str:
    """Deduce the parent prefix from the suffix.

    :param prefix: prefix string
    :type prefix: str
    :return: parent prefix
    :rtype: str
    """
    tokens = prefix.replace("-", "_").split("_")
    tokens = [t for t in tokens if t not in SUBTYPE_TOKENS]
    return "_".join(tokens)


SUBTYPE_RULES = {p: infer_parent_prefix(p) for p in classification.get("subtype_mapping", [])}

SUBTYPE_RULES

{'embl-cds': 'embl',
 'ensembl_pro': 'ensembl',
 'ensembl_trs': 'ensembl',
 'ensemblgenome_pro': 'ensemblgenome',
 'ensemblgenome_trs': 'ensemblgenome',
 'refseq_nt': 'refseq',
 'wbparasite_trs_pro': 'wbparasite',
 'wormbase_pro': 'wormbase',
 'wormbase_trs': 'wormbase'}

In [36]:
## INTERNAL_PREFIXES:
## if prefix.startswith("gene_")
## if prefix in {"crc64"}
## if prefix.endswith("-id")

INTERNAL_KEYWORDS = {
    "crc64",  ## only need UniProt checksum, not namespace
}


def is_internal_prefix(prefix: str) -> bool:
    prefix = prefix.lower()

    if prefix.startswith("gene_"):
        return True

    if prefix in INTERNAL_KEYWORDS:
        return True

    return bool(prefix.endswith("-id"))

In [32]:
INTERNAL_PREFIXES = {p for p in idmapping_prefixes if is_internal_prefix(p)}
INTERNAL_PREFIXES

{'crc64',
 'gene_name',
 'gene_orderedlocusname',
 'gene_orfname',
 'gene_synonym',
 'uniprotkb-id'}

In [33]:
DEPRECATED_PREFIXES = set(classification.get("deprecated_identifier", []))

In [34]:
def remap_prefix(prefix: str) -> dict:
    prefix = prefix.lower()

    if is_internal_prefix(prefix):
        return {"original": prefix, "canonical": None, "source": "internal"}

    if prefix in DEPRECATED_PREFIXES:
        return {"original": prefix, "canonical": None, "source": "deprecated"}

    if prefix in SUBTYPE_RULES:
        return {"original": prefix, "canonical": SUBTYPE_RULES[prefix], "source": "subtype"}

    normalized = br.normalize_prefix(prefix)
    if normalized:
        return {"original": prefix, "canonical": normalized, "source": "bioregistry"}

    return {"original": prefix, "canonical": None, "source": "unresolved"}

In [77]:
import pandas as pd

results = [remap_prefix(p) for p in sorted(idmapping_prefixes)]
df = pd.DataFrame(results)
df.head(25)

         original      canonical       source
0       allergome      allergome  bioregistry
1   arachnoserver  arachnoserver  bioregistry
2         araport        araport  bioregistry
3          biocyc         biocyc  bioregistry
4         biogrid        biogrid  bioregistry
5         biomuta            NaN   unresolved
6            ccds           ccds  bioregistry
7             cgd            cgd  bioregistry
8          chembl         chembl  bioregistry
9         chitars            NaN   unresolved
10       collectf            NaN   unresolved
11  complexportal  complexportal  bioregistry
12     conoserver     conoserver  bioregistry
13          cptac            NaN   unresolved
14          crc64            NaN     internal
15      dictybase      dictybase  bioregistry
16            dip            dip  bioregistry
17        disprot        disprot  bioregistry
18           dmdm            NaN   unresolved
19          dnasu            NaN   unresolved
20       drugbank       drugbank  bioregistry
21       echobase       echobase  bioregistry
22         eggnog         eggnog  bioregistry
23           embl            NaN   unresolved
24       embl-cds           embl      subtype

In [78]:
print(df["source"].value_counts())

source
bioregistry    56
unresolved     31
subtype         9
internal        6
deprecated      1
Name: count, dtype: int64

In [82]:
unresolved_df = df[df["source"] == "unresolved"].sort_values("original").drop(columns=["canonical"])
unresolved_df

               original      source
5               biomuta  unresolved
9               chitars  unresolved
10             collectf  unresolved
13                cptac  unresolved
18                 dmdm  unresolved
19                dnasu  unresolved
23                 embl  unresolved
29        ensemblgenome  unresolved
32               esther  unresolved
33              euhcvdb  unresolved
41          genereviews  unresolved
44           genomernai  unresolved
46           glyconnect  unresolved
47  guidetopharmacology  unresolved
51          japonicusdb  unresolved
53            legiolist  unresolved
54              leproma  unresolved
56               merops  unresolved
62                  oma  unresolved
63          opentargets  unresolved
66               patric  unresolved
69             pharmgkb  unresolved
70             phi-base  unresolved
73         proteomicsdb  unresolved
74            pseudocap  unresolved
83                 tair  unresolved
91            uniref100  unresolved
92             uniref50  unresolved
93             uniref90  unresolved
94            veupathdb  unresolved
96           wbparasite  unresolved

#### These are UniProt cross-reference databases.

Uniprot cluster resources not in bioregistry.

In [ ]:
## The mappings that already made when prefixes are existing in Bioregistry

print(br.normalize_prefix("tair"))
print(br.normalize_prefix("patric"))
print(br.normalize_prefix("oma"))
print(br.normalize_prefix("merops"))

None
None
None
None

These prefixes are for external biological databases not covered by the Bioregistry.

### Final Evaluation

Bioregistry was evaluated for prefix remapping.
- It directly recognizes 56 out of 103 observed prefixes;
- It correctly normalizes prefix variants; 
- 31 prefixes are not covered by Bioregistry; these correspond mainly to UniProt-specific resources.

After incorporating subtype rules, internal metadata handling and deprecated identifiers, ~70% of prefixes can be governed.